comments:
  giscus:
    enable: true
    repo: "chenrry666/chenrry666.github.io"
    repo_id: "MDEwOlJlcG9zaXRvcnkyNTcyMTgwNDU="
    category: "General"
    category_id: "DIC_kwDOD1TV_c4CViaw"
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "top"
    theme: "light"
    lang: "zh-CN"
    loading: "lazy"

favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

avatar:
  author_nickname: Chenrry666
  path: /

prevnext:
  enable: true

link: 
  -
    name: categories
    icon: bookmark
    path: /categories/
  -
    # 档案
    name: archives
    icon: updatetime
    path: /archives/
  -
    name: github
    icon: github
    path: https://github.com/chenrry666
    target: _blank
  -
    name: email
    icon: envelope
    path: mailto:chengruichen3@gmail.com
  # -
  #   name: facebook
  #   icon: facebooksquare
  #   path:
  # -
  #   name: twitter
  #   icon: twitter
  #   path:
  # -
  #   name: wechat
  #   icon: wechat
  #   path:
  # -
  #   name: weibo
  #   icon: weibo
  #   path:
  -
    name: rss
    icon: rss
    path: /atom.xml
    target: _blank

footer:
  -
    name: Copyright © Chenrry666 2022
    path: https://github.com/chenrry666
  -
    name: Theme by Leek | Powered by Hexo
    path: https://github.com/chenrry666/leek

search:
  enable: true
